name: Node
on:
  push:
    branches: [ "main" ]
jobs:
  deploy:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set up environment variables
        uses: SpicyPizza/create-envfile@v2.0
        with:
          env_key_DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          env_key_DISCORD_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}
          env_key_ADRIANNE_ID: ${{ secrets.ADRIANNE_ID }}
          env_key_MICO_ID: ${{ secrets.MICO_ID }}
          env_key_PAUL_ID: ${{ secrets.PAUL_ID }}
          env_key_NEO_ID: ${{ secrets.NEO_ID }}
          env_key_ICE_ID: ${{ secrets.ICE_ID }}
          env_key_ISAAK_ID: ${{ secrets.ISAAK_ID }}
          env_key_TRASH_SERVER_ID: ${{ secrets.TRASH_SERVER_ID }}
          env_key_TRASH_SERVER_GENERAL_CHANNEL_ID: ${{ secrets.TRASH_SERVER_GENERAL_CHANNEL_ID }}
          env_key_TRASH_SERVER_ECHO_CHANNEL_ID: ${{ secrets.TRASH_SERVER_ECHO_CHANNEL_ID }}
          env_key_PLAYGROUND_SERVER_ID: ${{ secrets.PLAYGROUND_SERVER_ID }}
          env_key_PLAYGROUND_SERVER_GENERAL_CHANNEL_ID: ${{ secrets.PLAYGROUND_SERVER_GENERAL_CHANNEL_ID }}
          directory: ./
          file_name: .env
          fail_on_empty: true
          sort_keys: false

      - name: Install dependencies
        run: |
          npm install
          npm run build

      - name: Start PM2
        run: |
          pm2 stop all
          pm2 start dist/index.js
